simbot:
  core:
    scan-package: pers.wuyou.robot
    logo:
      enable: false
    tips:
      enable: false
  component:
    mirai:
      protocol: ANDROID_PHONE
server:
  port: 8880
spring:
  profiles:
    active: test
  datasource: #数据库链接相关配置
    druid:
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD}
      url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${DATABASE}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      db-type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      testWhileIdle: true
      testOnBorrow: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      filter:
        wall:
          config:
            show-allow: true

mybatis-plus:
  mapper-locations: classpath:**/mapper/xml/*Mapper.xml, ./mapper/*.xml
  configuration:
    # 显示sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false

logging:
  level:
    ROOT: INFO
#    pers.wuyou.robot: DEBUG

# 点歌功能配置
music:
  tencent:
    account: ${QQ_UIN}
    password: ${QQ_PWD}
  netEase:
    account: ${NET_EASE_UIN}
    password: ${NET_EASE_PWD}
    server-host: http://82.156.174.44:3000/
# 项目域名
robot:
  host: http://robot.wuyourj.club/
  ip-host: http://118.195.154.251:8880/
  tianapi-key: ${TIANAPI_KEY}
