simbot:
  core:
    scan-package: pers.wuyou.robot
    logo:
      enable: false
    tips:
      enable: false
  component:
    mirai:
      protocol: ANDROID_PHONE
spring:
  profiles:
    active: test
logging:
  level:
    ROOT: INFO
    pers.wuyou.robot: DEBUG